













/* ====================================================================================================================
NOTES:
    Request
        ↓
    routing
        ↓
    matching route
        ↓
    apply behavior

    BEHAVIORS:
        serve file
        upload file
        delete file
        run CGI
        redirect
        directory listing
        error page
        session handling
        method validation
*/
