server {
    host 127.0.0.1
    ports 8080 8081
    server_name localhost

    client_max_body_size 10485760

    error_page 400 ./errors/400.html
    error_page 403 ./errors/403.html
    error_page 404 ./errors/404.html
    error_page 405 ./errors/405.html
    error_page 413 ./errors/413.html
    error_page 500 ./errors/500.html

    route / {
        methods GET
        root ./www
        index index.html
        directory_listing off
    }

    route /uploads_entries { 
        methods GET
        root ./www
        index uploads.html
        directory_listing off
    }

    route /uploads {
        methods POST
        root ./www/uploads
        directory_listing off
    }

    route /uploads/list {
        methods GET
        root ./www/uploads
        directory_listing on
    }

    route /redirect {
        redirect 301 /
    }

    route /uploads/delete {
        methods DELETE
        root ./www/uploads
        directory_listing off
    }

    route /cgi {
        methods GET POST
        root ./cgi-scripts
        cgi .py
    }

    route /admin {
        methods GET POST DELETE
        root ./www
        index admin.html
        directory_listing off
        cookie_required on
    }

}

server {
    host 127.0.0.1
    ports 8080
    server_name test.com

    client_max_body_size 5242880

    error_page 404 ./errors/404.html

    route / {
        methods GET
        root ./test_site
        index index.html
        directory_listing off
    }

}